version: '3.8'

services:
  laravel-zero:
    build:
      context: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_URL: ${DB_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

